insert into public.units (id, name, season, difficulty, order_index) values
  (1, 'Chemistry of Life', 'summer', 'hard', 1),
  (2, 'Cell Structure and Function', 'summer', 'hard', 2),
  (3, 'Cellular Energetics', 'summer', 'hard', 3),
  (4, 'Cell Communication and Cell Cycle', 'summer', 'hard', 4),
  (5, 'Heredity', 'fall', 'medium', 5),
  (6, 'Gene Expression and Regulation', 'fall', 'hard', 6),
  (7, 'Natural Selection', 'winter', 'medium', 7),
  (8, 'Ecology', 'spring', 'easy', 8)
on conflict (id) do update set
  name = excluded.name,
  season = excluded.season,
  difficulty = excluded.difficulty,
  order_index = excluded.order_index;

insert into public.chapters (id, unit_id, title, order_index) values
  ('1.1',1,'Water and Polarity',1),
  ('1.2',1,'Elements of Life',2),
  ('1.3',1,'Biological Macromolecules',3),
  ('1.4',1,'Properties of Enzymes',4),
  ('1.5',1,'Structure and Function',5),
  ('2.1',2,'Cell Structure',1),
  ('2.2',2,'Cell Size and Surface Area',2),
  ('2.3',2,'Membrane Transport',3),
  ('2.4',2,'Cell Compartmentalization',4),
  ('3.1',3,'Enzyme Catalysis',1),
  ('3.2',3,'Photosynthesis',2),
  ('3.3',3,'Cellular Respiration',3),
  ('3.4',3,'ATP and Coupled Reactions',4),
  ('3.5',3,'Metabolic Pathway Regulation',5),
  ('4.1',4,'Signal Transduction',1),
  ('4.2',4,'Feedback Mechanisms',2),
  ('4.3',4,'Cell Cycle',3),
  ('4.4',4,'Mitosis and Regulation',4),
  ('5.1',5,'Meiosis',1),
  ('5.2',5,'Mendelian Genetics',2),
  ('5.3',5,'Non-Mendelian Patterns',3),
  ('5.4',5,'Chi-Square and Probability',4),
  ('6.1',6,'DNA and RNA Structure',1),
  ('6.2',6,'DNA Replication',2),
  ('6.3',6,'Transcription',3),
  ('6.4',6,'Translation',4),
  ('6.5',6,'Gene Regulation and Mutation',5),
  ('7.1',7,'Natural Selection',1),
  ('7.2',7,'Hardy-Weinberg',2),
  ('7.3',7,'Population Genetics',3),
  ('7.4',7,'Speciation and Phylogeny',4),
  ('8.1',8,'Population Ecology',1),
  ('8.2',8,'Community Ecology',2),
  ('8.3',8,'Ecosystem Dynamics',3),
  ('8.4',8,'Human Impact',4)
on conflict (id) do update set
  unit_id = excluded.unit_id,
  title = excluded.title,
  order_index = excluded.order_index;
